version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "index.js"]
