name: Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile -t ghcr.io/${{ github.repository_owner }}/ghost-binger:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ghost-binger:latest
